require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ViewSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # ViewSession. As you add validations to ViewSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "session_id" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ViewSessionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all view_sessions as @view_sessions" do
      view_session = ViewSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:view_sessions).should eq([view_session])
    end
  end

  describe "GET show" do
    it "assigns the requested view_session as @view_session" do
      view_session = ViewSession.create! valid_attributes
      get :show, {:id => view_session.to_param}, valid_session
      assigns(:view_session).should eq(view_session)
    end
  end

  describe "GET new" do
    it "assigns a new view_session as @view_session" do
      get :new, {}, valid_session
      assigns(:view_session).should be_a_new(ViewSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested view_session as @view_session" do
      view_session = ViewSession.create! valid_attributes
      get :edit, {:id => view_session.to_param}, valid_session
      assigns(:view_session).should eq(view_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ViewSession" do
        expect {
          post :create, {:view_session => valid_attributes}, valid_session
        }.to change(ViewSession, :count).by(1)
      end

      it "assigns a newly created view_session as @view_session" do
        post :create, {:view_session => valid_attributes}, valid_session
        assigns(:view_session).should be_a(ViewSession)
        assigns(:view_session).should be_persisted
      end

      it "redirects to the created view_session" do
        post :create, {:view_session => valid_attributes}, valid_session
        response.should redirect_to(ViewSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved view_session as @view_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        ViewSession.any_instance.stub(:save).and_return(false)
        post :create, {:view_session => { "session_id" => "invalid value" }}, valid_session
        assigns(:view_session).should be_a_new(ViewSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ViewSession.any_instance.stub(:save).and_return(false)
        post :create, {:view_session => { "session_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested view_session" do
        view_session = ViewSession.create! valid_attributes
        # Assuming there are no other view_sessions in the database, this
        # specifies that the ViewSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ViewSession.any_instance.should_receive(:update_attributes).with({ "session_id" => "MyString" })
        put :update, {:id => view_session.to_param, :view_session => { "session_id" => "MyString" }}, valid_session
      end

      it "assigns the requested view_session as @view_session" do
        view_session = ViewSession.create! valid_attributes
        put :update, {:id => view_session.to_param, :view_session => valid_attributes}, valid_session
        assigns(:view_session).should eq(view_session)
      end

      it "redirects to the view_session" do
        view_session = ViewSession.create! valid_attributes
        put :update, {:id => view_session.to_param, :view_session => valid_attributes}, valid_session
        response.should redirect_to(view_session)
      end
    end

    describe "with invalid params" do
      it "assigns the view_session as @view_session" do
        view_session = ViewSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ViewSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => view_session.to_param, :view_session => { "session_id" => "invalid value" }}, valid_session
        assigns(:view_session).should eq(view_session)
      end

      it "re-renders the 'edit' template" do
        view_session = ViewSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ViewSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => view_session.to_param, :view_session => { "session_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested view_session" do
      view_session = ViewSession.create! valid_attributes
      expect {
        delete :destroy, {:id => view_session.to_param}, valid_session
      }.to change(ViewSession, :count).by(-1)
    end

    it "redirects to the view_sessions list" do
      view_session = ViewSession.create! valid_attributes
      delete :destroy, {:id => view_session.to_param}, valid_session
      response.should redirect_to(view_sessions_url)
    end
  end

end
